"""Added pinecone settings

Revision ID: 1b7fcdc71637
Revises: fded396a06e7
Create Date: 2026-02-26 15:37:47.689735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7fcdc71637'
down_revision = 'fded396a06e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinecone_api_key', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('pinecone_index_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pinecone_index_name')
        batch_op.drop_column('pinecone_api_key')

    # ### end Alembic commands ###
